### ISSUE TITLE
Voto SIM-condicionado

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/euvoto#6]
É uma sugestão que requer mais discussão para ser conceitualmente validada/apreciada, e que talvez, mesmo validada, seja mais trabalhosa de ser implementada. 

Nessa versão beta, onde a comunidade já está postando comentários bacanas nas votações, um tipo de comentário muito frenquente foi algo como _"... mas o texto da norma precisaria ser revisado..."_ ou _"aprovaria se o texto fosse revisado"_.

Uma quarta opção de voto, além do SIM/NÃO/ABSTENÇÃO, daria margem para atender às pessoas que fizeram esse tipo de comentário.  

PS: estou chamando de "SIM condicionado", mas pode ser qualquer outro nome.

**Comment by ppKrauss** [comment]
Incluindo mais uma informação importante. O Rangel me esclareceu como é o processo, ou seja, quando faria sentido votar "SIM-condicionado",
1. a maior parte dos Projetos de Lei que tem chegado ao  EuVoto já são "textos acabados", não faz sentido pedir para alterar o texto, de modo que não seria mais oportuno o "sim-condicionado".
2. eventualmente poderíamos convidar os vereadores a postar Projetos de Lei de um estágio anterior, justamente "para Consulta Pública"...  Para o vereador saber se o texto  demanda mais investimento de revisão (e aí os comentários do EuVoto também ajudam!), ou se o texto já está realmente acado e pode seguir em frente com segurança e apoio da comunidade. 

A relevância do item 2 isso ficou mais evidente na apresentação de ontem do Legislando (!).

**Comment by everton137** [comment]
@ppKrauss eu acho a ideia interessante, mas não está previsto nos entregáveis fazer isso. E eu acho que os votos devem simular a realidade, que é sim, não ou abstenção.

Para mim o uso dos comentários é super importante, inclusive para as pessoas chegarem num consenso e, daí sim, decidirem por algo. Se a pessoa está indecisa, para mim está OK abster-se.
